// -----------------------------------------------------------------------
// <copyright file="GlobalUsings.cs" company="lanedirt">
// Copyright (c) lanedirt. All rights reserved.
// Licensed under the MIT license. See LICENSE.md file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

// <auto-generated/>
// Note: this file is not actually auto-generated but the statement above is required because
// otherwise a lot of SA1200 checks will fail due to it not fully supporting GlobalUsings at time of writing.

global using AliasVault.WebApp.Main.Models;
global using AliasVault.WebApp.Services;
global using AliasVault.WebApp.Services.Auth;
global using AliasVault.WebApp.Services.Database;
