// <auto-generated>
// This file was automatically generated. Do not edit manually.


// src/webapi/AuthEventType.ts
var AuthEventType = /* @__PURE__ */ ((AuthEventType2) => {
  AuthEventType2[AuthEventType2["Login"] = 1] = "Login";
  AuthEventType2[AuthEventType2["TwoFactorAuthentication"] = 2] = "TwoFactorAuthentication";
  AuthEventType2[AuthEventType2["Logout"] = 3] = "Logout";
  AuthEventType2[AuthEventType2["TokenRefresh"] = 10] = "TokenRefresh";
  AuthEventType2[AuthEventType2["PasswordReset"] = 20] = "PasswordReset";
  AuthEventType2[AuthEventType2["PasswordChange"] = 21] = "PasswordChange";
  AuthEventType2[AuthEventType2["TwoFactorAuthEnable"] = 22] = "TwoFactorAuthEnable";
  AuthEventType2[AuthEventType2["TwoFactorAuthDisable"] = 23] = "TwoFactorAuthDisable";
  AuthEventType2[AuthEventType2["Register"] = 30] = "Register";
  AuthEventType2[AuthEventType2["AccountDeletion"] = 99] = "AccountDeletion";
  return AuthEventType2;
})(AuthEventType || {});

export { AuthEventType };
//# sourceMappingURL=index.js.map
//# sourceMappingURL=index.js.map