//-----------------------------------------------------------------------
// <copyright file="GlobalUsings.cs" company="aliasvault">
// Copyright (c) aliasvault. All rights reserved.
// Licensed under the AGPLv3 license. See LICENSE.md file in the project root for full license information.
// </copyright>
//-----------------------------------------------------------------------

// <auto-generated />

global using NUnit.Framework;
