//-----------------------------------------------------------------------
// <copyright file="GlobalUsings.cs" company="lanedirt">
// Copyright (c) lanedirt. All rights reserved.
// Licensed under the MIT license. See LICENSE.md file in the project root for full license information.
// </copyright>
//-----------------------------------------------------------------------

// <auto-generated />

global using NUnit.Framework;
