// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasServerDb.Migrations.SqliteMigrations
{
    /// <inheritdoc />
    public partial class UpdateAliasVaultEmailClaimNull : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_UserEmailClaims_AliasVaultUsers_UserId",
                table: "UserEmailClaims");

            migrationBuilder.AddForeignKey(
                name: "FK_UserEmailClaims_AliasVaultUsers_UserId",
                table: "UserEmailClaims",
                column: "UserId",
                principalTable: "AliasVaultUsers",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_UserEmailClaims_AliasVaultUsers_UserId",
                table: "UserEmailClaims");

            migrationBuilder.AddForeignKey(
                name: "FK_UserEmailClaims_AliasVaultUsers_UserId",
                table: "UserEmailClaims",
                column: "UserId",
                principalTable: "AliasVaultUsers",
                principalColumn: "Id");
        }
    }
}
