import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['cjs', 'esm'],
  target: 'es2020',
  dts: true,
  clean: true,
  splitting: false,
  minify: false,
  sourcemap: true,
  banner: {
    js: '// <auto-generated>\n// This file was automatically generated. Do not edit manually.\n',
  }
});
