import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/**/index.ts'],
  format: ['esm'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  treeshake: true,
  target: 'es2020',
  minify: false,
  banner: {
    js: '// <auto-generated>\n// This file was automatically generated. Do not edit manually.\n',
  }
});