// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasClientDb.Migrations
{
    /// <inheritdoc />
    public partial class _130UpdateIdentityStructure : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "AddressCity",
                table: "Aliases");

            migrationBuilder.DropColumn(
                name: "AddressCountry",
                table: "Aliases");

            migrationBuilder.DropColumn(
                name: "AddressState",
                table: "Aliases");

            migrationBuilder.DropColumn(
                name: "AddressStreet",
                table: "Aliases");

            migrationBuilder.DropColumn(
                name: "AddressZipCode",
                table: "Aliases");

            migrationBuilder.DropColumn(
                name: "BankAccountIBAN",
                table: "Aliases");

            migrationBuilder.DropColumn(
                name: "Hobbies",
                table: "Aliases");

            migrationBuilder.DropColumn(
                name: "PhoneMobile",
                table: "Aliases");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "AddressCity",
                table: "Aliases",
                type: "VARCHAR",
                maxLength: 255,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AddressCountry",
                table: "Aliases",
                type: "VARCHAR",
                maxLength: 255,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AddressState",
                table: "Aliases",
                type: "VARCHAR",
                maxLength: 255,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AddressStreet",
                table: "Aliases",
                type: "VARCHAR",
                maxLength: 255,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AddressZipCode",
                table: "Aliases",
                type: "VARCHAR",
                maxLength: 255,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "BankAccountIBAN",
                table: "Aliases",
                type: "TEXT",
                maxLength: 255,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Hobbies",
                table: "Aliases",
                type: "TEXT",
                maxLength: 255,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "PhoneMobile",
                table: "Aliases",
                type: "TEXT",
                maxLength: 255,
                nullable: true);
        }
    }
}
