// -----------------------------------------------------------------------
// <copyright file="GlobalUsings.cs" company="aliasvault">
// Copyright (c) aliasvault. All rights reserved.
// Licensed under the AGPLv3 license. See LICENSE.md file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

// <auto-generated/>
// Note: this file is not actually auto-generated but the statement above is required because
// otherwise a lot of SA1200 checks will fail due to it not fully supporting GlobalUsings at time of writing.

global using AliasVault.Client.Main.Models;
global using AliasVault.Client.Services;
global using AliasVault.Client.Services.Auth;
global using AliasVault.Client.Services.JsInterop;
global using AliasVault.Client.Services.Database;
