source 'https://rubygems.org'

# gem "jekyll", "~> 4.3.2"
gem "just-the-docs"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins
